### ISSUE TITLE
Limit characters on homepage subjects display

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/rp-ucd-client#103]
For the randomly displayed research subjects on the front page, we should limit the selected subjects to those that are under a certain number of characters so we don't end up would this sort of thing:

![Screen Shot 2021-02-01 at 10 47 25 AM](https://user-images.githubusercontent.com/17831969/106505004-8f6deb80-647c-11eb-9cd8-8b1eeb9ca2eb.png)

My preference would be to limit the characters to what fits as a single line in the 360px wide viewport so that we never have multi-line subjects on any device on the homepage view. I'm not entirely sure what that exact number is (and it's hard for me to figure out without the correct font live on sandbox), but my best guess is int he range of **35-40-ish characters**.

**Comment by spelkey-ucd** [comment]
@wrenaria. Long subjects on the homepage are now truncated with ellipses through CSS. 

If this solution doesn't work, we can exclude long subjects entirely by changing the query. The only issue is that this approach would require a whole new field at indexing, so it would add overhead.

**Comment by wrenaria** [comment]
@spelkey-ucd This is definitely a big improvement! I can live with this. Thank you!
