### ISSUE TITLE
CAS Id not matching user accounts

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-client#121]
The change in user identifiers to an opaque id has affected the matching of users to their accounts.  It appears that methodology assumed the [user path was CAS id](
https://github.com/ucd-library/rp-ucd-client/blob/9b40999b390b7b5b27d9fbf8c1dfb2665ac120e2/client/public/elements/pages/person/rp-page-person.js#L221) There should probably be a function, _getAccount(CASId) or similar that returns the account identifier.

**Comment by jrmerz** [comment]
deployed to sandbox at `v1.1.0-beta.44`

**Comment by jrmerz** [comment]
@qjhart please review and let me know how you want to go about patching rc

**Comment by qjhart** [comment]
@jrmerz yes go ahead and update `main` and submit the new image, and I'll pull it in.
