### ISSUE TITLE
Adjust breakpoint of quick search

### ISSUE THREAD

**Issue by spelkey-ucd** [ucd-library/rp-ucd-client#123]
Quick search should not drop to new line:

![image](https://user-images.githubusercontent.com/34284106/110171482-c6138a80-7dc9-11eb-96e3-a70950851716.png)

Rather, it should look like this:

![image](https://user-images.githubusercontent.com/34284106/110171554-e2172c00-7dc9-11eb-92db-58d91a9c24d9.png)

Just need to adjust it by a couple of pixels.

**Comment by wrenaria** [comment]
Not quite there for me on my phone (android/samsung s8, chrome). Looks like the button and text field aren't quite correctly aligned either. The horizontal lines should blend seamlessly into the right side circle button, no curves showing. 

<img src="https://user-images.githubusercontent.com/17831969/115074304-60c5b580-9eae-11eb-855a-a6b7916e05b6.jpg" width="350" >

**Comment by spelkey-ucd** [comment]
gold border should be around the container and not the input. i have no clue why i put it around the input initially. my bad.

**Comment by jrmerz** [comment]
This has been patch for layout issues with a rebuild coming: https://github.com/ucd-library/rp-ucd-client/issues/198
