### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#132]
Create page element for 404 page.  Designs coming from Kimmy.

**Comment by wrenaria** [comment]
Design Assets: https://drive.google.com/drive/folders/1aNLrRaRiW4eZVz7jcxImRyvTt0WNN5-u?usp=sharing 

Text:

`Oh no! This page has bolted away! Don’t worry, we’ll get you home.`

Desktop Design (481px+) | Specs 
--- | ---
![Desktop – 404](https://user-images.githubusercontent.com/17831969/112916066-a1eb5680-90b4-11eb-90e5-875800705c30.png) | ![Desktop – 406](https://user-images.githubusercontent.com/17831969/112916069-a44db080-90b4-11eb-80de-b3f94b52a89e.png)


Mobile Design | Specs
--- | ---
![360 – Mobile Search Results – All – 1](https://user-images.githubusercontent.com/17831969/112916049-99931b80-90b4-11eb-897f-aea052926361.png) | ![360 – Mobile Search Results – All – 2](https://user-images.githubusercontent.com/17831969/112916054-9b5cdf00-90b4-11eb-9c1d-02cbda24be18.png)

**Comment by Vensberg** [comment]
I am reopening this issue for Kimmy to review. It looks fine to me.

**Comment by wrenaria** [comment]
Horse image breaks the frame on mobile and allows side to side scrolling beyond edge of website. This should not happen. Need to fix that before I can sign off on this.
