### ISSUE TITLE
Create schema.org publication transform

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#145]
Given a VIVO Publication object (https://wiki.lyrasis.org/display/VIVODOC110x/Publication+Model), the transform should spit out a schema.org ScholarlyArticle object (https://schema.org/ScholarlyArticle).  This should be isomorphic, ie run in both Node and browser JS lands.

**Comment by jrmerz** [comment]
This may need to support vivo:ConferencePaper as well.  @qjhart  ?

**Comment by qjhart** [comment]
Yes, for potential differentiation.  We should include the vivo type for all publications as well, even though they won't necessarily be used in any schema.org specific context, it wouldn't hurt to show.

**Comment by jtyzzer** [comment]
I don't think indicating the title as a "headline" is necessarily wrong given that it's a property inherited from CreativeWork--of which ScholarlyArticle is a subtype--but it seems less applicable here that it would be to, say, a news article.

**Comment by jtyzzer** [comment]
Looking at Bryan Jenkins, I see jobTitle represented as 

```
"jobTitle": [
    "AGRON AES-B/E/E",
    "PROF-FY-B/E/E",
    "DEPARTMENT CHAIR",
    "Chair and Professor"
  ],
```
In the [Schema.org](https://schema.org/jobTitle) example, there's this example:
```
"jobTitle": {
        "@type": "DefinedTerm",
        "inDefinedTermSet": "https://targetjobs.co.uk/careers-advice/job-descriptions",
        "termCode": "277133-aid-workerhumanitarian-worker-job-description",
        "name": "Aid worker/humanitarian worker",
        "url": "https://targetjobs.co.uk/careers-advice/job-descriptions/277133-aid-workerhumanitarian-worker-job-description"
    }
```
Perhaps our jobTitle should be changed to an array of name objects, e.g.,
```
 "jobTitle": [
    {
      "@type": "Text",
      "name": "AGRON AES-B/E/E"
    },
    {
      "@type": "Text",
      "name": "PROF-FY-B/E/E""
    },
    {
      "@type": "Text",
      "name": "DEPARTMENT CHAIR""
    },
    {
      "@type": "Text",
      "name": "Chair and Professor"
    }
  ]
```
Re: "knowsAbout," the application of DefinedTerms to people appears to be an AE (JM) innovation, as  [this](https://schema.org/DefinedTerm) page doesn't appear to depict that but rather limits terms to describing a work's aboutness.
