### ISSUE TITLE
Create schema.org Book transform

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#146]
Given a BIBO Book object, the transform should spit out a schema.org Book object (https://schema.org/Book). This should be isomorphic, ie run in both Node and browser JS lands.

**Comment by jrmerz** [comment]
hasName can be an array: 
https://github.com/ucd-library/rp-ucd-client/blob/sandbox/lib/schema-org-transforms/book.js#L30

**Comment by jtyzzer** [comment]
Reviewed on 4/12/2021. No issues found.
