### ISSUE TITLE
Updates to the FAQ

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#159]
FAQ doc (https://docs.google.com/document/d/1Qbkxe5Yp79s0AMUXy0X9LB54PYXMi1JmAzetlN-PiCg/edit#heading=h.5iysipdh59ba) has been updated.  Make sure text matches in faq page.  Screenshots need to be added.

**Comment by Vensberg** [comment]
In question "How do I change the visibility of the fields in my profile?", the link off the word "here" should redirect to question "How do I edit my publication record?".

**Comment by jrmerz** [comment]
@Vensberg the link already points to "How do I edit my publication record?". I can have it open the question as well if you would like.

**Comment by Vensberg** [comment]
@jrmerz Let's do that. Otherwise it looks like nothing happens.
