### ISSUE TITLE
"Show more" feature for research areas

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#166]
If a faculty selects more than 4 research areas/subject terms in Elements, AE will show the first 4 and allow showing more if the user wants that (similar to how the publications are displayed).

**Comment by Vensberg** [comment]
Looks good.

**Comment by Vensberg** [comment]
I am reopening this issue for Kimmy to review. It looks fine to me.

**Comment by wrenaria** [comment]
Can we use the "more-horiz" iron icon instead of text for the ellipses?

**Comment by jrmerz** [comment]
@wrenaria I'm assuming you want that for the homepage as well?

**Comment by wrenaria** [comment]
@jrmerz Yes please!
