### ISSUE TITLE
Grants Profile Block UI

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/rp-ucd-client#167]
This is the basic UI for Grant block on the people's profiles. Rules for layout and breaks follow the rules for other parts of profiles. 

If you're looking for margin rules/breaks rules, check here: https://drive.google.com/drive/u/1/folders/1yjwMrc1nu1jll7zFB9RM977NIoCGK_h5

![Desktop – Profile - Grant Block – 1](https://user-images.githubusercontent.com/17831969/113462940-2d782680-93d8-11eb-989f-62d9249e30e8.png)

Image is hopefully self-explanatory, but
- Grants are sorted by Active and Complete
- Each grant displays a title linked to full info page
- Under the title show data for: year range for the grant, grant type, the person's role in the grant, and who warded the grant.
- Grants are ordered by most recent start date

**Comment by jrmerz** [comment]
@sbagg please include a flag to specifically hide this block until the 1.3 release is ready.

**Comment by wrenaria** [comment]
Looks like there are a couple things to adjust:

- Grants are in the wrong order. Grants need to display with the most recently award grant displaying first in the list, oldest last. Right now it's opposite of that.
- The words "Awarded by" need to appear before the funding agency. 
- If there is "No Role Assigned" ([example](https://sandbox.experts.ucdavis.edu/person/89a1040b3138c28a893ecc9865721efa)), just hide the role title completely.
