### ISSUE TITLE
Links to elements should open in new tab

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#174]
All links to elements should be opened with target="_blank"

**Comment by Vensberg** [comment]
1. The new tab opens fine. 
2. I'll ask Kimmy whether the Edit Publications box on the AE tab should go away.
3. Also for Kimmy, why there are quotation marks around publications in the box (Edit "Publications")
I'll check back in with @jrmerz once I have a better idea what to do with 2 and 3.

**Comment by Vensberg** [comment]
I opened a new issue for the requests above, so I am closing this one.
