### ISSUE TITLE
Publication formatting issues in gold.experts

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#180]
1. Publications listed in a profile do not list the profile user as an author. Eg. http://gold.experts.library.ucdavis.edu:8080/person/ae63d3a620682adb8440914428e50c33
2. A few of the users appear both as the "featured" author on a publication's landing page and also in the list of Other Authors: e.g.: http://gold.experts.library.ucdavis.edu:8080/work/3266506. In this case, if you navigate to the person's profile, the publication citations will include them in the author list.
3. This publication has empty space authors: http://gold.experts.library.ucdavis.edu:8080/work/2196063. I don't see many of those.

**Comment by jrmerz** [comment]
1. Is a UI issue
2. I think is UI.  @qjhart remind me how we are handing the case when there is two entries in the Authorship for the same user (ex: vcard entry and 'real' user entry)
3. The author names are missing. I'd say both data and UI.  Mostly data but UI should better handle the case.

**Comment by jrmerz** [comment]
recording for the record:

`This is should be the rule for every time you format a citation, 1) Only ever use the authorships that have a rank, and only ever use the #vcard associated with those authorship.`

**Comment by jrmerz** [comment]
@Vensberg @qjhart Everything but the missing data for item 3 on this list is live on Sandbox.   Should I move to QA or wait?

**Comment by qjhart** [comment]
@Vensberg as far as I can see item 3 on this list is also fixed, https://sandbox.experts.ucdavis.edu/work/2196063  The names may be out of order, but that's because the citation source lumps the whole name in as a lastname

**Comment by Vensberg** [comment]
I agree 1 is fixed.
Part of 2 is still there--https://sandbox.experts.ucdavis.edu/work/3266506, scroll all the way down to UC Davis Authors--it has FB, JD, and then under other authors--again JD, FB. By the way this is a new issue--the first names and last names are switched, so the comma is no longer needed.
The initial issue on 3 is resolved, but in https://sandbox.experts.ucdavis.edu/work/2196063 the list of Other Authors all start with ", ".

**Comment by qjhart** [comment]
@Vensberg , Yes. Please see the note above regarding unranked users.  SInce JDFB identified themselves as author for this citation, none of the source citations include a link from his citation entry to his account, so we have no way to know, and since trying to match names won't generally work, we are not trying to do that.

This is why IMHO,  we should *only* add linked users in that section.  The authors in the citation at the top is much better display.

**Comment by Vensberg** [comment]
@qjhart "we should only add linked users in that section. The authors in the citation at the top is much better display." If I understand correctly, you are proposing dropping the section "Other Authors". That's fine with me.

"Unranked authorships should never affect the citation *formatting* in anyway."--we may be using different definitions of citation formatting. To me it sounds like dropping unranked authors from something that looks like this: "Scales and scaling as a framework for synthesizing irrigated agroecosystem research on the westside San Joaquin Valley Wallender WW, Hopmans JW, Grismer M. 5:99-122. " but that is obviously not the case. Do you have other examples of unranked authors?

**Comment by qjhart** [comment]
@Vensberg , I imagine we should run that  `Other Authors` question by Kimmy, but that's good :) Let me see if I can get  a list of unranked authors, that don't have a ranked connection.

**Comment by qjhart** [comment]
@Vensberg regarding #3, I think that @jrmerz and team probably have family and given name transposed in that last section, but it is an indication of the issue we are dealing with making those consistent.  The citation we have shows this for example:

```ttl<http://experts.ucdavis.edu/authorship/2196063-1#vcard-name>
        a       <http://www.w3.org/2006/vcard/ns#Name> ;
        <http://www.w3.org/2006/vcard/ns#familyName>
                "Fernández-Bayo" ;
        <http://www.w3.org/2006/vcard/ns#givenName>
                "Jesús D" .

<http://experts.ucdavis.edu/authorship/2196063-2#vcard-name>
        a       <http://www.w3.org/2006/vcard/ns#Name> ;
        <http://www.w3.org/2006/vcard/ns#familyName>
                "Blake A. Simmons" .
```
 The first entry is correct, the second no.  Shows why ordering by family name is hard :)

**Comment by qjhart** [comment]
@Vensberg / @jrmerz I suggest we tentatively comment out the other authors section, pending final review by Kimmy.

**Comment by wrenaria** [comment]
Hiding Other Authors list is fine by me, they appear in the header anyway.

**Comment by Vensberg** [comment]
@wrenaria, I had another thought on this topic. What if the UC Davis Authors goes away as well, and instead the UCD authors are hyperlinked in the header of the publication?

**Comment by qjhart** [comment]
@Vensberg, we can potentially add that as an addition, but it doesn't work in the general case, Like Bayo's publications.  Elements hasn't linked the citation to a particular author, so we have no way of linke Bayo to his name in the citation.  So you'd need a plan for those unranked associations.

**Comment by Vensberg** [comment]
Same problem over and over then. OK, let's shelve this for now.

**Comment by qjhart** [comment]
@jrmerz I'm having to reopen this issue based on some new citations.  This testing is on the dev branch.  If we look at: 

https://dev.experts.ucdavis.edu/person/5b15a7d5e96cf0f89d475ba730e77c4b we see the following publications:

![image](https://user-images.githubusercontent.com/344953/117065289-29dc0600-acdc-11eb-8e4e-767b5dcc38f3.png)

However a quick review of the vcards for that citation, show another name being used: 

```sparql
PREFIX work: <http://experts.ucdavis.edu/work/>
PREFIX authorship: <http://experts.ucdavis.edu/authorship/>

describe ?v WHERE {
  values ?v { work:3460688 authorship:3460688-1 
  <http://experts.ucdavis.edu/authorship/3460688-1#vcard> 
    <http://experts.ucdavis.edu/authorship/3460688-1#vcard-name> 
  }
}
```

```ttl
work:3460688  a                   <http://experts.ucdavis.edu/schema#work> , bibo:AcademicArticle ;
        rdfs:label                "Defining velocities for accurate kinetic statistics in the Grønbech-Jensen Farago thermostat." ;
        <http://experts.ucdavis.edu/schema#insertionDateTime>
                "2021-05-04T01:12:08.147+00:00"^^xsd:dateTime ;
        <http://experts.ucdavis.edu/schema#lastModifiedDateTime>
                "2021-05-03T09:01:43.833-07:00"^^xsd:dateTime ;
        bibo:doi                  "10.1103/physreve.101.022123" ;
        bibo:issue                "2-1" ;
        bibo:journal              "Physical review. E" ;
        bibo:status               bibo:published ;
        bibo:volume               "101" ;
        vivo:dateTimeValue        <http://experts.ucdavis.edu/work/3460688#date> ;
        vivo:hasPublicationVenue  <http://experts.ucdavis.edu/venue/issn:2470-0045> ;
        vivo:relatedBy            authorship:3460688 , authorship:3460688-1 , authorship:3460688-2 .

<http://experts.ucdavis.edu/authorship/3460688-1#vcard-name>
        a                 vcard:Name ;
        vcard:familyName  "Grønbech-Jensen" ;
        vcard:givenName   "Niels" .

authorship:3460688-1  a  <http://experts.ucdavis.edu/schema#authorship> , vivo:Authorship ;
        vivo:favorite  "false" ;
        vivo:rank      1 ;
        vivo:relates   <http://experts.ucdavis.edu/authorship/3460688-1#vcard> , work:3460688 , <http://experts.ucdavis.edu/person/5b15a7d5e96cf0f89d475ba730e77c4b> .

<http://experts.ucdavis.edu/authorship/3460688-1#vcard>
        a              vcard:Individual ;
        vcard:hasName  <http://experts.ucdavis.edu/authorship/3460688-1#vcard-name> .

```

**Comment by qjhart** [comment]
To me this is not workable.  We *always* need to use the citation provided vcard, at least until/if we implement an uber citation, and even then we need to maintain the published name.  There will *always* be a citation provided name for every ranked user, so we can relay on that.  The reason's to provide the expert in the authorship is so we can (if we wanted/needed) hyperlink the appropriate name back to the expert (and of course provide the list of authorships to the expert)

I thein the post processing needs updating, so that it doesn't select a best, but provdes the vcard info, and the link to the expert if they exist, so 

I feel like the work record eg;  https://dev.experts.ucdavis.edu/api/record/ucdrp:work/3460688

```json
{
"volume": "101",
"Authorship": [
{
"@id": "ucdrp:authorship/3460688-2#vcard",
"@type": "vcard:Individual",
"vivo:rank": 2,
"relatedBy": "ucdrp:authorship/3460688-2",
"hasName": {
"@id": "ucdrp:authorship/3460688-2#vcard-name",
"familyName": "Farago",
"givenName": "Oded"
}
},
{
"@id": "ucdrp:authorship/3460688-1#vcard",
"@type": "vcard:Individual",
"vivo:rank": 1,
"relatedBy": "ucdrp:authorship/3460688-2",
"hasName": {
"@id": "ucdrp:authorship/3460688-1#vcard-name",
"familyName": "Grønbech-Jensen" ,
"givenName": "Niels" 
},
{
"@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b",
"vivo:rank": 1,
"relatedBy": [
"ucdrp:authorship/3460688",
"ucdrp:authorship/3460688-1"
]}
"@type": [
"experts:work",
"bibo:AcademicArticle"
],
"hasPublicationVenue": {
"@id": "ucdrp:venue/issn:2470-0045",
"eissn": "2470-0053",
"issn": "2470-0045",
"label": "Physical review. E"
},
"@id": "ucdrp:work/3460688",
"label": "Defining velocities for accurate kinetic statistics in the Grønbech-Jensen Farago thermostat.",
"publicationDate": "2020-02-01T00:00:00",
"doi": "10.1103/physreve.101.022123"
}
```
