### ISSUE TITLE
Odd UCD E-link

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#185]
When I click on UCD Elinks of this work https://sandbox.experts.ucdavis.edu/work/3178763, I get https://ucelinks.cdlib.org/sfx_local?id=doi:10.13031/TRANS.13519. It looks very different from the standard page that opens for other publications

**Comment by jrmerz** [comment]
@Vensberg All works I have looked at seem to render about the same. Some do render content on the left and some on the right.  Regardless, we are for the most part providing the DOI in the url and then it is up to https://ucelinks.cdlib.org/ to render that page.  Not sure what you would like us to do here.

Can you provide more information to help provide what action you would like us to take on this issue?

@qjhart FYI

**Comment by qjhart** [comment]
@Vensberg yes, there's no magic here, we let ucelinks do it's magic.  I know the less information you have, the worse that can be, but that DOI is resolving okay on their site.

**Comment by Vensberg** [comment]
I don't know if you did anything, but it looks normal now: https://ucelinks.cdlib.org/sfx_local?id=doi:10.1021/acsami.0c09417. The previous one resulted in being taken eventually to the journal landing page, not the article itself.
