### ISSUE TITLE
v1.2 homepage tweaks

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#189]
Initial description: move the search box into the same color section as the intro blurb, remove the egghead image, and center everything

**Comment by wrenaria** [comment]
Here's the final look for this:

![Screen Shot 2021-04-15 at 3 22 02 PM](https://user-images.githubusercontent.com/17831969/114945532-5d72f100-9dfe-11eb-9dc0-dfbcc63e377b.png)

- Aggie gold (#ffbf00) is used for header text. 
- White for body copy. 
- Image has been optimized for web and is located in the Assets folder on Drive. Direct link to image: https://drive.google.com/file/d/1HePGCAPAWInyQzA9X1g0c3OfI30b3RvD/view?usp=sharing

The image should look pretty good at most screen sizes using object-fit: cover. It'll just look like subtle texture on small screens, which is fine. Mobile example:

![Screen Shot 2021-04-15 at 3 20 38 PM](https://user-images.githubusercontent.com/17831969/114945583-78ddfc00-9dfe-11eb-8f6f-e0d389878fc8.png)

**Comment by wrenaria** [comment]
Looks great on desktop, but missing the right and left margins on my phone.

<img src="https://user-images.githubusercontent.com/17831969/115073736-99b15a80-9ead-11eb-8d64-06c453a2b6a5.jpg" width="350" >

**Comment by jrmerz** [comment]
This is not showing on all devices (or dev tools at 360px).  I have tagged this as a specific phone issue here: https://github.com/ucd-library/rp-ucd-client/issues/199
