### ISSUE TITLE
Homepage margins breaking on some mobile phones

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#199]
This is not showing on every phone, but here is a sample from G8 Samsung.

![115073736-99b15a80-9ead-11eb-8d64-06c453a2b6a5](https://user-images.githubusercontent.com/1852393/115081378-00884100-9eb9-11eb-8288-e4dc0a1e82e1.jpg)

JM is having trouble replicating. First step will be getting a dev a device that is showing this issue.

**Comment by jrmerz** [comment]
@spelkey-ucd Are you able to replicate this on your phone?

**Comment by spelkey-ucd** [comment]
Nope. Looks fine on my iphone 11 on ios 14.4.2.

- SP

From: Justin Merz ***@***.***>
Reply-To: ucd-library/rp-ucd-client ***@***.***>
Date: Monday, April 19, 2021 at 11:04 AM
To: ucd-library/rp-ucd-client ***@***.***>
Cc: Stephen A Pelkey ***@***.***>, Mention ***@***.***>
Subject: Re: [ucd-library/rp-ucd-client] Homepage margins breaking on some mobile phones (#199)


@spelkey-ucd<https://github.com/spelkey-ucd> Are you able to replicate this on your phone?

**Comment by wrenaria** [comment]
Unfortunately this is still broken for me (Samsung Galaxy S8). :\ 

<img src="https://user-images.githubusercontent.com/17831969/121062953-95514180-c77a-11eb-91c3-d6d56e2b6ad7.jpg" width="350">

**Comment by wrenaria** [comment]
This continues to look the same as pictured in my previous comment on both mine and my partner's phones (both Samsungs -- galaxy s8 and s20).

**Comment by jrmerz** [comment]
This is a bug I have not fully tracked down, but as the screenshot shows, the Samsung Chrome phones are bleeding over the padding.  This was actually happening on Chrome Pixel phones as well, but only by a couple pixels.  It was rendering correctly on the iphone.  

The workaround fix required a complete redo of the that panel, so please review carefully to ensure I did not introduce any new bugs.

![Screen Shot 2021-07-01 at 7 30 46 AM](https://user-images.githubusercontent.com/1852393/124142329-fea53700-da3e-11eb-9ae7-af422ce42317.png)

**Comment by wrenaria** [comment]
Needs a bit more spacing under the yellow header/above white body text. Otherwise, looks good on my phone.
