### ISSUE TITLE
Double publication

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#204]
This person has the same publication twice under Chapter (2)
https://dev.experts.ucdavis.edu/person/0bbbc8e338eeaade56057f875d2bfe9e

The one difference is that one abstract has "Taylor & Francis Group" and the other doesn't. This may be incorrectly deduped on the ELements side.

**Comment by jrmerz** [comment]
@qjhart this seems like a data issue, they are two different works.

**Comment by qjhart** [comment]
@Vensberg  These are two separate citations that are identified as different in scopus: 

https://oapolicy.universityofcalifornia.edu/viewobject.html?id=2764134&cid=1 and 

https://oapolicy.universityofcalifornia.edu/viewobject.html?id=3092932&cid=1

This has to be resolved by the user or proxy.    Reassigning it back to you.  It's interesting, they just recently claimed that publication.

**Comment by Vensberg** [comment]
Moving this to 1.3

**Comment by Vensberg** [comment]
Scopus had duplicate entries. Those are now resolved in Scopus, but the changes can't be reflected in Elements (I am not sure if that's because the citations were already claimed). If the user brings this up, this is the correct entry: https://oapolicy.universityofcalifornia.edu/viewobject.html?id=3092932&cid=1 and he can delete the other one.
