### ISSUE TITLE
Citation formatting

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#205]
There are a couple of odd formatting of citations on the profiles of users. 
Type 1:
Nitrogen and COD Removal from Septic Tank Wastewater in Subsurface Flow Constructed Wetlands: Plants Effects.  Collison RS,  Grismer M.  1061-4303. 87:1999-2007.
I don't know what 1061-4303. is and whether we need it at all.

Type 2:
Evolution of the materials and methods used for subsurface drainage of agricultural lands from antiquity to the present  Yannopoulos SI,  Grismer M,  Bali KM,  Angelakis AN.  12.
That last number looks odd. Also, is there no data on the volume and pages?

Some have both types. 

Imaging Metal Halide Perovskites Material and Properties at the Nanoscale  Howard JM,  Lahoti R,  Leite M.  1614-6832. 10.

**Comment by jrmerz** [comment]
Links for above examples
1) https://dev.experts.ucdavis.edu/person/1c5fa66384bd620d750c07bf8250cd9a
2) https://dev.experts.ucdavis.edu/1c5fa66384bd620d750c07bf8250cd9a

**Comment by Vensberg** [comment]
3. https://dev.experts.ucdavis.edu/person/9e13a6eaf5513cfdadb4e0dd467338e7

**Comment by jrmerz** [comment]
The formatting is [issn]. [volume]:[pageStart]-[pageEnd].

For the first example (Mark)
1) The Nitrogen Removal paper has all 4 values
2) The Evolution of materials only has volume

**Comment by Vensberg** [comment]
Ah. Let's get rid of ISSN. I've never seen it appear on a citation (but export into the RIS file as is now)

**Comment by Vensberg** [comment]
The pagination is missing in the Scopus source in Elements (but actually exists in Dimensions and CrossRef). Can these sources be called upon to fill in the page gap?

**Comment by jrmerz** [comment]
Ok, but I feel like that is not solving the real bug as the Journal name is normally part of a citation and is just not properly joined (the Journal Title not joining being bug).

@Vensberg rather than just dropping, I'm assuming you would like the Journal text name, if available?  And if not, then show nothing?

**Comment by Vensberg** [comment]
@jrmerz yes, that sounds like a good approach.

**Comment by Vensberg** [comment]
Closing the issue here and opening in RP 1.3 because there a lot of additional data review and prep needed for further enhancements
