### ISSUE TITLE
Doubling of some names

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#206]
Klaus Van Bethem and Jean VanderGheyst's names in the profile drop-down are repeated.
<img width="270" alt="doubled name" src="https://user-images.githubusercontent.com/26015534/115784853-856cd200-a373-11eb-8ece-b60af9577551.png">

**Comment by jrmerz** [comment]
fixed here fd1dbf0068cdfaddb182e833295dee5a8a698cdf

**Comment by Vensberg** [comment]
I still see the problem in dev.

**Comment by jrmerz** [comment]
This card is still in progress, I'll move the card to QA when deployed and ready for review.
