### ISSUE TITLE
Publication download takes too long

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#207]
The publication RIS file takes too long to download (I give up waiting) for more than 6 papers.

**Comment by jrmerz** [comment]
@Vensberg can you provide an example url (person)?

**Comment by Vensberg** [comment]
https://dev.experts.ucdavis.edu/person/5291e4d36b94d14caae13c84f7bc5662

**Comment by Vensberg** [comment]
This is an example of someone with 6 publications, whose file I can eventually download, if you need to time it: https://dev.experts.ucdavis.edu/person/9e13a6eaf5513cfdadb4e0dd467338e7

**Comment by jrmerz** [comment]
@qjhart Issue seems to be with this query: https://github.com/ucd-library/vessel/blob/dev/api/models/miv/publications.tpl.rq

**Comment by jrmerz** [comment]
fixed here: https://github.com/ucd-library/vessel/commit/c8de0b8e477b1d6cb74ee1c435174eec70357b6a (messed up commit message tag)
