### ISSUE TITLE
Hide grant award amount

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#215]
The grant amount should be hidden until the researcher decides to reveal it. I'll talk to Kimmy about how the reveal should be depicted.

@sbagg sections should be hidden if there is grant amount

**Comment by jrmerz** [comment]
This is a major feature we do not currently have a solution for.  Fuseki and Elastic Search are exposed to the public.  Even if we where to hide the field in Elastic Search, the value would still be publicly available via Fuseki.  This means the visibility of award amount (or any opt in/out field) would need to be known at harvest time, making this a harvester issue.

@qjhart

**Comment by qjhart** [comment]
Agreed, we are working under the assumption that *anything* in the experts linked database is public, and therefore, we need to make that available to the harvester (or conceivably sooner, to FIS) so it isn't propagated.  Technically, it's not hard, the trick is in the fact that this is local information, and our goal is to not jump over that fence until after the first prototype.

Realistically, we could pretty easily work w/ CDL to get some of these flags to the profile, but it would probably look strange to the other UCs.  

![image](https://user-images.githubusercontent.com/344953/116760603-330e5f80-a9ca-11eb-8267-344e8250c36d.png)

**Comment by Vensberg** [comment]
We should discuss purchasing the grants module.

**Comment by Vensberg** [comment]
1. The grants module can accept grant amounts. 
2. For now we are leaving the grant amounts off the data that we are pulling into Aggie Experts. 
3. We'll revisit this topic at a later time.
