### ISSUE TITLE
Multiple ODR positions not being shown

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-client#216]
For users, like https://rc.experts.ucdavis.edu/person/5b15a7d5e96cf0f89d475ba730e77c4b, the expert has multiple ODR titles,  but only the first is being shown.

You can see this person at: https://org.ucdavis.edu/search/directory_results.shtml?id=00133366

```json
[
  {
    "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#odr-1",
    "identifier": "odr-1",
    "vivo:rank": 1,
    "familyName": "Jensen",
    "givenName": "Niels",
    "hasEmail": {
      "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#odr-1-email",
      "@type": [
        "vcard:Work",
        "vcard:Email"
      ],
      "email": "ngjensen@ucdavis.edu"
    },
    "organization": "Mech & Aero Engr",
    "title": "Professor"
  },
  {
    "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#pps-2",
    "identifier": "pps-2",
    "vivo:rank": 12,
    "familyName": "Jensen",
    "givenName": "Niels",
    "hasEmail": {
      "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#pps-2-email",
      "@type": [
        "vcard:Work",
        "vcard:Email"
      ],
      "email": "ngjensen@ucdavis.edu"
    },
    "organization": "MATHEMATICS",
    "title": "PROF-AY"
  },
  {
    "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#odr-2",
    "identifier": "odr-2",
    "vivo:rank": 2,
    "familyName": "Jensen",
    "givenName": "Niels",
    "hasEmail": {
      "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#odr-2-email",
      "@type": [
        "vcard:Work",
        "vcard:Email"
      ],
      "email": "ngjensen@ucdavis.edu"
    },
    "organization": "Mathematics",
    "title": "Professor"
  },
  {
    "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#odr-4",
    "identifier": "odr-4",
    "vivo:rank": 4,
    "familyName": "Jensen",
    "givenName": "Niels",
    "hasEmail": {
      "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#odr-4-email",
      "@type": [
        "vcard:Work",
        "vcard:Email"
      ],
      "email": "ngjensen@ucdavis.edu"
    },
    "organization": "Applied Science",
    "title": "Professor"
  },
  {
    "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard",
    "identifier": "oap-1",
    "vivo:rank": 20,
    "familyName": "Jensen",
    "givenName": "Niels"
  },
  {
    "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#odr-3",
    "identifier": "odr-3",
    "vivo:rank": 3,
    "familyName": "Jensen",
    "givenName": "Niels",
    "hasEmail": {
      "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#odr-3-email",
      "@type": [
        "vcard:Work",
        "vcard:Email"
      ],
      "email": "ngjensen@ucdavis.edu"
    },
    "organization": "COSMOS, Statewide Office",
    "title": "Executive Director"
  },
  {
    "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#pps-1",
    "identifier": "pps-1",
    "vivo:rank": 11,
    "familyName": "Jensen",
    "givenName": "Niels",
    "hasEmail": {
      "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#pps-1-email",
      "@type": [
        "vcard:Work",
        "vcard:Email"
      ],
      "email": "ngjensen@ucdavis.edu"
    },
    "organization": "MECHANICAL & AEROSPACE ENGR",
    "title": "PROF-AY-B/E/E"
  }
]
```

![image](https://user-images.githubusercontent.com/344953/116828143-bad2a600-ab51-11eb-8c66-3f699b284ea6.png)

**Comment by qjhart** [comment]
@wrenaria I've added the direcotory to the top of the above  card.

**Comment by wrenaria** [comment]
I'm thinking we use primary ODR listing as primary/top level profile title display and then show additional listing titles as "Additional Roles" in the About section. The primary listing info will not be repeated here, so this info will only show for users that have chosen to create multiple listings in ODR.

Mockup using the example user linked in Quinn's original comment:

![AE-AdditionalRoles](https://user-images.githubusercontent.com/17831969/116938080-0d2dc880-ac1f-11eb-8a61-17cf1bb91cf1.png)

**Comment by qjhart** [comment]
@jrmerz, there  are a few errors in the updated code: 

In the [current code](https://github.com/ucd-library/rp-ucd-client/blob/89676f33c5b1ebc40e39d1c0cc238f7d31f943a0/client/public/src/models/PersonModel.js#L132), we check against the ucd:identifier.  This is because these were originally blank nodes, in the [new code](https://github.com/ucd-library/rp-ucd-client/blob/dc0072d2407d326ccf76fb4c4a76bad8dc310898/client/public/src/models/PersonModel.js#L122), we are checking the @id, value; which we can do but that has been changed, just need to know that plan

```json
"@id": "ucdrp:person/825ce359f69a5b6b72412590d4913a79#vcard-odr-1",
"identifier": "odr-1",
```

In addition in the [current code](https://github.com/ucd-library/rp-ucd-client/blob/89676f33c5b1ebc40e39d1c0cc238f7d31f943a0/client/public/src/models/PersonModel.js#L134) first ODR, and then PPS are exclusionary codes, but in the new code, only ODR is.
