### ISSUE TITLE
Allow for preferred pronouns

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-client#225]
Following [harvest updates](https://github.com/ucd-library/rp-ucd-harvest/issues/43), we have added `vcard:pronoun` to an individual.  There is no order to multiple entries.  We need to decide how we display pronouns on a users' page.  Need a design, then quick implementation.  To date, I think only Quinn has a record in the experts system.

**Comment by Vensberg** [comment]
@wrenaria can you work on a design that includes preferred pronouns on the Aggie Experts profile? The section should not show if they are not listed.

**Comment by wrenaria** [comment]
Preferred pronouns display in parenthesis and centered, under the main position title, default font size (16) using color ucdblue10 / #CDD6E0.

Looks like pronouns is an open field in ODR, so here's a couple examples of how they might appear:

![Screen Shot 2021-05-17 at 4 38 18 PM](https://user-images.githubusercontent.com/17831969/118569294-81dc2900-b72e-11eb-8113-e0fbfac0b261.png)

![Screen Shot 2021-05-17 at 4 38 28 PM](https://user-images.githubusercontent.com/17831969/118569297-84d71980-b72e-11eb-9c6e-271d15f03602.png)

**Comment by pbrantley** [comment]
I’m a comma guy. Ymmv.

From: Kimmy H ***@***.***>
Date: Monday, May 17, 2021 at 16:44
To: ucd-library/rp-ucd-client ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [ucd-library/rp-ucd-client] Allow for preferred pronouns (#225)

Preferred pronouns display in parenthesis and centered, under the main position title, default font size (16) using color ucdblue10 / #CDD6E0.

Looks like pronouns is an open field in ODR, so here's a couple examples of how they might appear:

[Screen Shot 2021-05-17 at 4 38 18 PM]<https://user-images.githubusercontent.com/17831969/118569294-81dc2900-b72e-11eb-8113-e0fbfac0b261.png>

[Screen Shot 2021-05-17 at 4 38 28 PM]<https://user-images.githubusercontent.com/17831969/118569297-84d71980-b72e-11eb-9c6e-271d15f03602.png>

**Comment by Vensberg** [comment]
Commas it is.

**Comment by Vensberg** [comment]
Looks good to me. Leaving for @wrenaria to sign off.

**Comment by wrenaria** [comment]
The text is there, but the styles are not: Pronoun text should be default font size (16) using color ucdblue10 / #CDD6E0.
