### ISSUE TITLE
NaN shows up as a year for a publication

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#234]
This publication https://rc.experts.ucdavis.edu/work/2816532 when viewed on this profile https://rc.experts.ucdavis.edu/person/03d481b0407c9f14beb561b595bb41f7 shows NaN as the year of publication (click on  view more in Academic Articles to see it). The article was published in 2019.

**Comment by qjhart** [comment]
@Vensberg / @jrmerz.  The VIVO schema only has a publication `date` predicate.  Elements has both a `publicationDate` and an `onlinePublicationDate`.  The current setup maintains consistency by mapping both of these to the date field.  As a result we have this VIVO definition....

```ttl 
<http://experts.ucdavis.edu/work/2816532>
        a       <http://purl.org/ontology/bibo/AcademicArticle> , <http://experts.ucdavis.edu/schema#work> ;
        <http://vivoweb.org/ontology/core#dateTimeValue>
                <http://experts.ucdavis.edu/work/2816532#date> ;
        .

<http://experts.ucdavis.edu/work/2816532#date>
        a       <http://vivoweb.org/ontology/core#DateTimeValue> ;
        <http://vivoweb.org/ontology/core#dateTime>
                "2019-05-23T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> , "2019-05-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        <http://vivoweb.org/ontology/core#dateTimePrecision>
                <http://vivoweb.org/ontology/core#yearMonthPrecision> , <http://vivoweb.org/ontology/core#yearMonthDayPrecision> .
```

This results in the following elastic search item (via vessel)

```json
{
"@type": ["bibo:AcademicArticle","experts:work"],
"@id": "ucdrp:work/2816532",
"publicationDate": ["2019-05-23T00:00:00","2019-05-01T00:00:00"],
"doi": "10.1002/ces2.10007"
}
```
Then, in the publication display: https://rc.experts.ucdavis.edu/person/03d481b0407c9f14beb561b595bb41f7
`publicationDate` is expected to be a scalar which results in a `NaN` designation.  

I think if we conform to the VIVO spec, then we should allow multiple dates, and so this should be an rp-client issue checking for array values for date, and showing (I suggest) only the earliest date. 

Alternatively, we could add a digital date to the VIVO schema.

**Comment by Vensberg** [comment]
@qjhart It should be the latest date. For some reason the paper publication date supersedes the epub one.

**Comment by jrmerz** [comment]
deployed to sandbox

**Comment by Vensberg** [comment]
Looks good.
