### ISSUE TITLE
Text needs to wrap in Browse

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/rp-ucd-client#235]
Right now in Browse pages, it looks like long items are displayed with ellipses instead of wrapping to the next line. Text need to wrap instead.

This is an example of why ellipses are not an adequate solution:

<img src="https://user-images.githubusercontent.com/17831969/121070201-465bda00-c783-11eb-8b1a-4fad5bbc5c2e.jpg"  width="300">

These are all different subjects, but you cannot tell that because the text that differentiates them is hidden.

**Comment by Vensberg** [comment]
Looks good to me. Leaving for @wrenaria to sign off.
