### ISSUE TITLE
Grants don't have a "Show 10 more" button

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#237]
For example, https://dev.experts.ucdavis.edu/person/9e684b3c3e621157fd375a7a5615afb4 has 30 total, but only 5 show, and there is no button to display the rest.

**Comment by Vensberg** [comment]
Looks good on sandbox.

**Comment by Vensberg** [comment]
The button is not showing on dev.

**Comment by jrmerz** [comment]
@qjhart there are updates to sandbox that are waiting for deployment to dev
