### ISSUE TITLE
ODR last name should be displayed

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#238]
This person https://dev.experts.ucdavis.edu/person/1b59b4daa533afdad6b6b17c998e2b8a is displayed as Tina Jeoh in ODR https://org.ucdavis.edu/search/directory_results.shtml?filter=Tina%20Zicari.

**Comment by jrmerz** [comment]
The ODR last name is being displayed.  Currently the data feed has two last names in ODR, the client is currently picking the first from the array and rendering.

@qjhart is there any other data bits from the ODR feed that can help pick which to display?

**Comment by qjhart** [comment]
@jrmerz This is fixed in the new data feed, see dev.experts.library.ucdavis.edu
