### ISSUE TITLE
Title wrap vs cut-off

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#243]
When you look at the dev home page, the titles of the featured people are shown in full, and somewhat overwhelm the name. I like the way the titles are cut off at a certain length, the way it is on rc. @wrenaria,  I am not sure if this was a design change. Please, weigh in.

<img width="921" alt="title_wrap" src="https://user-images.githubusercontent.com/26015534/124996343-a00f2880-dffd-11eb-9d8b-7e43086b0b75.png">

**Comment by jrmerz** [comment]
proposal to push to v1.4?

**Comment by wrenaria** [comment]
Vessela like the title truncated on the homepage and I'm fine with leaving as for this design iteration of the site. Can address name/title scale issues during brand update.

**Comment by Vensberg** [comment]
OK to push to 1.4

**Comment by Vensberg** [comment]
A similar problem appears on this page https://rc.experts.ucdavis.edu/concept/FoR/0912 where the subject area bubbles run off the white area into the right gray margin
