### ISSUE TITLE
Broader scope not displaying on subjects

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#244]
Example https://dev.experts.ucdavis.edu/concept/FoR/130301 is empty, https://rc.experts.ucdavis.edu/concept/FoR/130301 has Specialist Studies in Education as a broader scope. Same for https://dev.experts.ucdavis.edu/concept/FoR/130102, and all other FoR I checked.
Strangely, vocabulary terms with both broader and narrower terms or just narrower terms display correctly: https://dev.experts.ucdavis.edu/concept/FoR/0201, https://dev.experts.ucdavis.edu/concept/FoR/02

**Comment by jrmerz** [comment]
I see no difference between:
https://dev.experts.ucdavis.edu/concept/FoR/130301
https://rc.experts.ucdavis.edu/concept/FoR/130301

![Screen Shot 2021-07-08 at 3 37 13 PM](https://user-images.githubusercontent.com/1852393/124999143-655bbf00-e002-11eb-8079-5412336f474f.png)
![Screen Shot 2021-07-08 at 3 37 48 PM](https://user-images.githubusercontent.com/1852393/124999185-75739e80-e002-11eb-91b1-672cc75b8ce9.png)

or
https://dev.experts.ucdavis.edu/concept/FoR/130102
https://dev.experts.ucdavis.edu/concept/FoR/130102
![Screen Shot 2021-07-08 at 3 38 59 PM](https://user-images.githubusercontent.com/1852393/124999278-9fc55c00-e002-11eb-890d-b8787b499487.png)
![Screen Shot 2021-07-08 at 3 39 15 PM](https://user-images.githubusercontent.com/1852393/124999307-ab188780-e002-11eb-88bf-cf1e6cf31a77.png)

**Comment by Vensberg** [comment]
It is gone now for me as well.
