### ISSUE TITLE
Formatting of long journal titles-volume-publication date on the publication landing page looks off

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#245]
Maybe put the volume and date on a new line? (https://dev.experts.ucdavis.edu/work/1878359)

<img width="716" alt="record_formatting" src="https://user-images.githubusercontent.com/26015534/124998048-8fac7d00-e000-11eb-9990-aedc0ebfda5f.png">

**Comment by jrmerz** [comment]
I would propose this goes to the next release.

**Comment by Vensberg** [comment]
OK. Can you start it?

**Comment by jrmerz** [comment]
Already created.  It's switched.

**Comment by Vensberg** [comment]
This issue has been taken care of by correcting the title of the journal. Unless another citation from an unusually titled journal appears, no adjustments are needed.
