### ISSUE TITLE
Display ODR websites + emails under Roles and remove position title from profile header

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/rp-ucd-client#256]
Some users with multiple positions also have a website associated with each position and/or an alternate email address. In order to maintain context for these links, we will keep the role website and email colocated with the associated role. This necessitates a number of changes.

We need to:

- [x] Change the "Additional Roles" section to be titled "Roles"
- [x] Remove the position title currently used in the header for all users and add it to the top of the "Roles" list
- [x] Remove the "Contact" section from profiles and relocate the email to display under the associated role next to an envelope icon.
- [x] Add a wesbite icon and link to the URL associated with the position. Please strip out any **http**, **www**, or ending slashes in the front-facing URL display (it both looks nicer and is less text for a screenreader to read).

## Icon Assets
For URLS, we use will the same icon from the design for the Website section (issue #220), which is also the same one campus uses on SiteFarm directories: [Font Awesome network-wired](**url**); here is an [SVG of the network-wired icon](https://drive.google.com/file/d/1YmtSRW_GQ7LxmoT8TsVzfpn6QG2W9oQN/view?usp=sharing).

For email, we will use [Font Awesome envelope](https://fontawesome.com/v5.15/icons/envelope?style=solid); here is an [SVG of the envelope icon](https://drive.google.com/file/d/1ZiV9hB4Bqj7bfQEGghw0-zNrSyVdFj5b/view?usp=sharing).

Color for these icons #73ABDD. 

## Mockup of Design Changes
![Web 1920 – Profile – Websites – 7](https://user-images.githubusercontent.com/17831969/127229532-c3f29db8-d288-438d-889a-3385e5cd818d.png)

Example above uses Niels Jensen's information.
- [Profile on sandbox](https://sandbox.experts.ucdavis.edu/person/5b15a7d5e96cf0f89d475ba730e77c4b)
- [ODR listing](https://org.ucdavis.edu/search/directory_results.shtml?filter=Niels%20Jensen)

**Comment by qjhart** [comment]
@sbagg  There are two locations for website locations now.  Each role, and have *one* associated URL, but then the websites section on the RHS can have multiple ones.

All of this data are in the vcard entries for the users.  For example, in Niels case: the [Person](http://localhost:8080/api/record/ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b) API call includes the emails, and links in the ODR sections of the vcard: 

```json
    "hasContactInfo": [
        {
            "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-oap-1",
            "familyName": "Jensen",
            "givenName": "Niels",
            "identifier": "oap-1",
            "vivo:rank": 20
        },
        {
            "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-odr-4",
            "familyName": "Jensen",
            "givenName": "Niels",
            "identifier": "odr-4",
            "middleName": "Gronbech",
            "organization": "Applied Science",
            "title": "Professor",
            "vivo:rank": 4
        },
        {
            "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-pps-2",
            "familyName": "Jensen",
            "givenName": "Niels",
            "hasEmail": {
                "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-pps-2-email",
                "@type": "vcard:Email",
                "email": "ngjensen@ucdavis.edu"
            },
            "identifier": "pps-2",
            "middleName": "Gronbech",
            "organization": "MATHEMATICS",
            "title": "PROF-AY",
            "vivo:rank": 12
        },
        {
            "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-odr-2",
            "familyName": "Jensen",
            "givenName": "Niels",
            "hasEmail": {
                "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-odr-2-email",
                "@type": "vcard:Email",
                "email": "ngjensen@math.ucdavis.edu"
            },
            "hasURL": {
                "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-odr-2-url",
                "url": "https://www.math.ucdavis.edu/research/profiles/ngjensen"
            },
            "identifier": "odr-2",
            "middleName": "Gronbech",
            "organization": "Mathematics",
            "title": "Professor",
            "vivo:rank": 2
        },
        {
            "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-odr-3",
            "familyName": "Jensen",
            "givenName": "Niels",
            "hasURL": {
                "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-odr-3-url",
                "url": "http://cosmos.ucop.edu"
            },
            "identifier": "odr-3",
            "middleName": "Gronbech",
            "organization": "COSMOS, Statewide Office",
            "title": "Executive Director",
            "vivo:rank": 3
        },
        {
            "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-pps-1",
            "familyName": "Jensen",
            "givenName": "Niels",
            "hasEmail": {
                "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-pps-1-email",
                "@type": "vcard:Email",
                "email": "ngjensen@ucdavis.edu"
            },
            "identifier": "pps-1",
            "middleName": "Gronbech",
            "organization": "MECHANICAL & AEROSPACE ENGR",
            "title": "PROF-AY-B/E/E",
            "vivo:rank": 11
        },
        {
            "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-odr-1",
            "familyName": "Jensen",
            "givenName": "Niels",
            "hasEmail": {
                "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-odr-1-email",
                "@type": "vcard:Email",
                "email": "ngjensen@ucdavis.edu"
            },
            "hasURL": {
                "@id": "ucdrp:person/5b15a7d5e96cf0f89d475ba730e77c4b#vcard-odr-1-url",
                "url": "http://faculty.engineering.ucdavis.edu/jensen/"
            },
            "identifier": "odr-1",
            "middleName": "Gronbech",
            "organization": "Mech & Aero Engr",
            "title": "Professor",
            "vivo:rank": 1
        }
    ],

```

**Comment by Vensberg** [comment]
Most of it looks good to me. In this case https://dev.experts.ucdavis.edu/person/ae63d3a620682adb8440914428e50c33, the two roles use the same email. @wrenaria, in those cases do you want the email to appear twice? This question doesn't have to resolve for this release to be completed. If the answer is "no", but everything else looks good, let's open a different issue, and close this one.

**Comment by wrenaria** [comment]
I think we have to keep both email locations even though it's redundant in this case. If a person has 3 roles, for example, and two use the same email but a third uses a different one, that would need to be clear.

These roles are positioned too closely together though. It's looks like one entry, not two separate entries. They should have the same space between them as you see between Publications below so that they are more easily differentiated as two separate role entries. 

![Screen Shot 2021-11-01 at 9 56 29 AM](https://user-images.githubusercontent.com/17831969/139710094-4ee9a50f-2127-4626-b9d5-f983158d399f.png)

**Comment by Vensberg** [comment]
I don't see the spacing between roles that Kimmy requested.

**Comment by sbagg** [comment]
All of this is on branch that is not pulled in yet into dev just running through the checks.  I will move it back and over again when the branch is pulled through
