### ISSUE TITLE
`<ae-factoid>` update home page.

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-client#266]
These [mockups](https://xd.adobe.com/view/de30b058-921b-4666-8021-ac2a604abc7e-8b63/screen/66a611d8-a606-4d84-9589-126702dac47d) show a home page with a factoid based look. 

We need to use the [example component](https://github.com/ucd-library/ucdlib-theme/blob/0b9d2531e05a566432f3c5421e5997094c65f61e/test-app/pages/page-infographics.js#L34) as a base to add factoids to the AE homepage.

**Comment by wrenaria** [comment]
Icons used in the mockup are from Font Awesome. Included bellow is both a link to the Font Awesome page for each icon + a link to an SVG version that has been manually reformatted to 24px square (Iron icon style). 

**People:** [fa-users](https://fontawesome.com/v5.15/icons/users?style=solid) | [svg](https://drive.google.com/file/d/1TfdXocRsUeqvKRmeecogl49zrjy4CTKi/view?usp=sharing)

**Works:** [fa-book-open](https://fontawesome.com/v5.15/icons/book-open?style=solid) | [svg](https://drive.google.com/file/d/16JkocQGZlnhLUoWYxMMkUwyUf8b7aV9E/view?usp=sharing)

**Subjects:** [fa-lightbulb-on](https://fontawesome.com/v5.15/icons/lightbulb-on?style=solid) | [svg](https://drive.google.com/file/d/1Ay97A-t3E5EYerZVJhItjXDWgokg6EwI/view?usp=sharing)

**Grants:** [fa-hand-holding-usd](https://fontawesome.com/v5.15/icons/hand-holding-usd?style=solid) | [svg](https://drive.google.com/file/d/1kOGuGVQ6MJMP1jHJVgMqn8AGyJ_1mfRF/view?usp=sharing)

**Courses:** [fa-chalkboard-teacher](https://fontawesome.com/v5.15/icons/chalkboard-teacher?style=solid) | [svg](https://drive.google.com/file/d/1zKc7O9fb3yYZRWdlL2DT2360oFr9LPHY/view?usp=sharing)

**Patents:** [fa-award](https://fontawesome.com/v5.15/icons/chalkboard-teacher?style=solid) | [svg](https://drive.google.com/file/d/18f4p2ghMOPeWfgAt1y5dfNeZUvB7niYN/view?usp=sharing)

**Comment by wrenaria** [comment]
Font is indeed too bold.

**Comment by Vensberg** [comment]
I'll make a separate issue for the font and close this one.
