### ISSUE TITLE
Homepage Redesign Question

### ISSUE THREAD

**Issue by sbagg** [ucd-library/rp-ucd-client#273]
@wrenaria I made the changes to the homepage per the XD file and I were wondering about the badges in the recently updated section.  They are filled in with color like the file, but this also affects other badges on the application like in the people's tabs, so they are all full color now instead of outlined.  Did you want all of the badges to be a full color like the one on the homepage or did you want different formatted badges for the homepage vs the other pages?

![Screen Shot 2021-10-12 at 1 36 40 PM](https://user-images.githubusercontent.com/42234329/137026301-10b26e2b-0e06-4126-9427-6c0ed61d393b.png)
![Screen Shot 2021-10-12 at 1 36 52 PM](https://user-images.githubusercontent.com/42234329/137026306-9e4cac5b-7dd0-4adb-8229-47d1105d5f57.png)
![Screen Shot 2021-10-12 at 1 37 09 PM](https://user-images.githubusercontent.com/42234329/137026309-dd50f6ac-71a7-4057-81e1-696e20735f96.png)

**Comment by wrenaria** [comment]
We just chatted over Zoom about this are on the same page now. 

In short: 
1. Using the same style on the subject buttons site wide is definitely the plan, but I haven't been given the opportunity/any allotted time to work out the rebrand on other pages yet, so not 100% certain whether they will be solid or border-only like they are on current site, but leaning towards solid.
2. This version/coloration of the homepage should not hit user eyes until we have built the full rebrand version that includes header and other content layout changes.
