### ISSUE TITLE
Remove 'Web of Science' Links

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-client#28]
The Web of Science Link on the citations is not built by the client, but is a part of the citation information (from the current XSLT processing)   Because the XSLT choose Web-of-science preferentially, for records, these are the links that come up.  In our database wos-lite has the most links, however other citation sources also include *different* links .

**Comment by qjhart** [comment]
@Vensberg, we could instead of removing, change the title to something like *Citation Provided Link* or I think the best thing to do would be remove the links from the linked database.

**Comment by Vensberg** [comment]
The number of links gets overwhelming, and it doesn't add anything new. I don't know what the best strategy to achieve that.
