### ISSUE TITLE
Hide Empty Sections  - grants, publications

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#283]
For example, here: https://dev.experts.ucdavis.edu/person/13d4e9c24bcb11b059b33f1db2136bae

**Comment by qjhart** [comment]
There seem to be two issues here.  First, we need @wrenaria to weigh in on this.  One problem I see here is that the components also need to work in the other contexts (Other websites, where the title might be required).  So, if we want multiple setups, we should decide how to do that for *all* the components in the same way, and I guess to decide  if they aren't included or hidden in some way, where I'll need @jrmerz input.

**Comment by wrenaria** [comment]
Blocks without data should be hidden from public view. It's okay to show them for logged in user since they can edit them to add data (like publications).

**Comment by qjhart** [comment]
@jrmerz will this work okay when used on external sites?

**Comment by Vensberg** [comment]
Almost there. It works when the publications are missing, like here:
https://dev.experts.ucdavis.edu/person/b8bbd1e76f1b76c87fe36975ab5a2b2e
And when both publications and grants are missing, like here
https://dev.experts.ucdavis.edu/person/a931045c07d1691940067a0bb59fc099

But it doesn't work when only grants are missing:
https://dev.experts.ucdavis.edu/person/1ba9ec4755deaa2806ff7094f5fc7257
