### ISSUE TITLE
Grant font differences

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#285]
The font for active and completed grants is different:
https://dev.experts.ucdavis.edu/person/3ecdb8764ec41106ef66af929761249e
https://dev.experts.ucdavis.edu/person/c16a4ff65bafbe8631a5f01cc127b2d7
The font is consistent in rc.

**Comment by qjhart** [comment]
This is a repeat of: #272, and was fixed with this patch, https://github.com/ucd-library/rp-ucd-client/commit/89a05e4430a39dc01f80a7de19e838f3ae53a50e  that didn't make it into dev.
