### ISSUE TITLE
Remove MIV question from FAQ

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-client#29]
@vensberg wants the MIV question removed.

**Comment by qjhart** [comment]
@Vensberg, I've rewritten the FAQ to include a generic export question, and moved to the bottom.  See image.  I figure we need some indication of the export, but we can also remove completely.

![image](https://user-images.githubusercontent.com/344953/95660942-06ebc980-0ae0-11eb-8a9f-0ba1dd8a8c40.png)

Comment, and reassign to @qjhart

**Comment by Vensberg** [comment]
Sounds good. Some edits: delete[Currently] **W**e only allow downloads for each user**'**s own publications. Once you are logged into the system, navigate to the Publications section of your profile. You will see a download button in the upper right-hand corner.
