### ISSUE TITLE
Identify subject for "view all X" items accessed via subject pages

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/rp-ucd-client#294]
![Screen Shot 2021-12-02 at 2 29 58 PM](https://user-images.githubusercontent.com/17831969/144513618-b347cb9d-50e7-43b4-9812-f95937de8955.png)

When you browse to a Subject (Example: [Engineering](https://rc.experts.ucdavis.edu/concept/FoR/09)) and click on the "View All Related `Category`" button, it takes you to a browsable A-Z list limited to that subject. Currently, the subject is not identified on the that page. 

It would be helpful to identify the subject at the top of the page. I would like to do that as a button. When the "X" on the yellow subject button is clicked, remove the blue area and show an unfiltered view of the standard Browse UI.

This capability should be applied to any type of content associated with the Subject that is too long to display all at once within the page (works, people). 

![Web 1920 – Subject - Engineering Works 2](https://user-images.githubusercontent.com/17831969/144513295-cc56c9b9-5262-4368-bd22-d300de7c1daa.png)

![Web 1920 – Subject - Engineering People notes](https://user-images.githubusercontent.com/17831969/144513165-80c02f9f-eb0d-4e3c-9756-2bd020814ad8.png)

### Long subject example:

![Screen Shot 2021-12-02 at 2 25 15 PM](https://user-images.githubusercontent.com/17831969/144513193-3740e3d7-9961-47a6-bc35-39051de39e60.png)

![Screen Shot 2021-12-02 at 2 25 39 PM](https://user-images.githubusercontent.com/17831969/144513205-27c00b96-5de9-4bb3-9e42-672591803f49.png)

**Comment by Vensberg** [comment]
Right now clicking on the alphabet will re-run the search. The original search must be kept in place. Same for grants and people.

**Comment by qjhart** [comment]
@sbagg - There are a number of  issues here: 

- For the rp-page-works.js page, we need to know if we have a `subject` query.  If we do, then we need to add the bar on the top of the page, that identifies the subject term.  

- If they click on the x, then that subject term is removed; eg `https://rc.experts.ucdavis.edu/works/articles?az=d&subject=concept/FoR/09` => https://rc.experts.ucdavis.edu/works/articles/`

- Right now, when users click the works type (eg articles), then the subject carries through.  This needs to work for the alphabet as well; eg
`https://rc.experts.ucdavis.edu/works/articles?az=d` becomes `https://rc.experts.ucdavis.edu/works/articles?az=d&subject=concept/FoR/09`

This works similarly for the `people` page.  However, 

-though the subject term seems to be extended into the query, the query is not properly responding.
- The counts do not include the search term
-

**Comment by Vensberg** [comment]
I don't see any changes--the list of researchers within a subject still cuts off at 10, without any options to view more.

**Comment by Vensberg** [comment]
The researcher problem is fixed in https://github.com/ucd-library/rp-ucd-client/issues/296.  @qjhart The alphabetic problem is fixed, but now segmenting the works into, for example, articles and conference papers and a letter of the alphabet together doesn't work. Try https://dev.experts.library.ucdavis.edu/works/articles?subject=concept%2FFoR%2F0913, switch to conference papers and click on "M".  I am OK with opening a separate issue for another release if this would take too much time to fix.

**Comment by wrenaria** [comment]
Functionally it appears to be working correctly. 

Visually, I desire two changes:
- I'd prefer about 5px more space between the X icon and the subject text so there's better visual separation. Right now it squishes into it almost like it is part of the word. 
- There's also extra white space above the blue block that shouldn't be there and should be removed (see [search result](https://dev.experts.library.ucdavis.edu/search?s=engineering) for a correct example to compare to the ["view all" subject results](https://dev.experts.library.ucdavis.edu/people?subject=concept%2FFoR%2F0905) with extra white space below)

![Screen Shot 2022-02-22 at 1 38 11 PM](https://user-images.githubusercontent.com/17831969/155224384-18e97afc-44b8-4f9e-a28b-5d67ad1056a5.png)
