### ISSUE TITLE
Add a "view all related people" button to people section of subject pages

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/rp-ucd-client#296]
If there are more than 10 people associated with a subject, add a "view all related people" button that functions like the ones we use in the works section. This is related to issue #294.

**Comment by qjhart** [comment]
@sbagg, Hmm, I noted in #294 that for the people, the querry doesn't seem to be working....

My quick review of the client seems to indicate the query is broken.

- though the subject term seems to be extended into the query, the query is not properly responding.
- The counts do not include the search term

Investigating further, we see that this [searech](https://rc.experts.ucdavis.edu/people?subject=concept/FoR/09) results in this ES bad query:  

``` json
{
  "offset": 0,
  "limit": 8,
  "sort": [
    {
      "hasContactInfo.familyName": "asc"
    }
  ],
  "filters": {
    "@type": {
      "type": "keyword",
      "op": "and",
      "value": [
        "experts:person"
      ]
    },
    "hasResearchArea": {
      "type": "keyword",
      "op": "and",
      "value": [
        "ucdrp:concept/FoR/09"
      ]
    }
  },
  "facets": {
    "@type": {
      "type": "facet"
    }
  }
}
```
Instead we need to use `hasResearchArea.@id` as in: 
``` json
{
  "offset": 0,
  "limit": 8,
  "sort": [
    {
      "hasContactInfo.familyName": "asc"
    }
  ],
  "filters": {
    "@type": {
      "type": "keyword",
      "op": "and",
      "value": [
        "experts:person"
      ]
    },
    "hasResearchArea.@id": {
      "type": "keyword",
      "op": "and",
      "value": [
        "ucdrp:concept/FoR/09"
      ]
    }
  },
  "facets": {
    "@type": {
      "type": "facet"
    }
  }
}
```

Which works.

**Comment by Vensberg** [comment]
Looks good to me. Leaving to @wrenaria to sign off.

**Comment by wrenaria** [comment]
Functionally it appears to be working correctly. 

Visually, I desire two changes:
- I'd prefer about 5px more space between the X icon and the subject text so there's better visual separation. Right now it squishes into it almost like it is part of the word. 
- There's also extra white space above the blue block that shouldn't be there and should be removed (see [search result](https://dev.experts.library.ucdavis.edu/search?s=engineering) for a correct example to compare to the ["view all" subject results](https://dev.experts.library.ucdavis.edu/people?subject=concept%2FFoR%2F0905) with extra white space below)

![Screen Shot 2022-02-22 at 1 38 11 PM](https://user-images.githubusercontent.com/17831969/155224384-18e97afc-44b8-4f9e-a28b-5d67ad1056a5.png)
