### ISSUE TITLE
Pagination in People needed

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#297]
When browsing People in alphabetical order, there should be pagination at the bottom at the page the same way it exists for Subjects, Works, etc. (already checked in with @wrenaria) on that

**Comment by sbagg** [comment]
I'm a little confused about the context of this question, where is the location that this is happening?  I originally thought it was in the search page in the sub facets of people but those seem to have pagination, so can you give me an example of this occurrence?

**Comment by Vensberg** [comment]
Looks good.
