### ISSUE TITLE
Subject Term overwrites

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-client#299]
A problem appears on this page https://rc.experts.ucdavis.edu/concept/FoR/0912 where the subject area bubbles run off the white area into the right gray margin.   This is similar to the previous overrun issue #243

**Comment by qjhart** [comment]
@Vensberg dev has this fix, but following the notes from #243, the subject are cut-off with a `...` rather than going to another line.  Assuming that's correct.

**Comment by Vensberg** [comment]
@qjhart, I am OK with ..., but it currently it links to the landing page of the preceding subject. 

@wrenaria can you weigh in? Are you OK with ... in general? Would it be preferable for ... to unfurl the rest of the subjects when clicking on it? In any case, let's make sure it doesn't redirect to the preceding subject. This is the url to look at and you need to be on the staff VPN: https://dev.experts.library.ucdavis.edu/concept/FoR/0912.

**Comment by Vensberg** [comment]
Now '...' redirects to a hidden subject

**Comment by qjhart** [comment]
@sbagg examples include:  https://dev.experts.library.ucdavis.edu/people or, https://dev.experts.library.ucdavis.edu/concept/FoR/0912, anywhere the badge contaners are.  
The overflow istruncated to the dots, but you can still link to the first hidden badge in the region after the ...


![image](https://user-images.githubusercontent.com/344953/151864239-7d144dfc-53c7-404a-9a60-49f442ab86bb.png)
