### ISSUE TITLE
One search context

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-client#318]
The works,  person, and grants search should be combined into a single default search. This requires

- [x] Collating all the searches so the proper fields are searched
- [x] Updating the client for a default searh only
- [x] Updating the client admin page.

**Comment by qjhart** [comment]
@Vensberg, default searches should look good for all types, and the order should be constant when switching to people, works, and grants.

**Comment by qjhart** [comment]
@Vensberg  eg. https://dev.experts.library.ucdavis.edu/search?s=engineering

**Comment by Vensberg** [comment]
Looks good.
