### ISSUE TITLE
Homepage Citation Counts / Works Citations

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-client#33]
We have updated the citations to include multiple citation types.  The Homepage does not reflect this additional items.

```json
{
  "total": 771,
  "offset": 0,
  "limit": 0,
  "results": [],
  "aggregations": {
    "facets": {
      "@type": {
        "ucdrp:publication": 757,
        "bibo:AcademicArticle": 617,
        "vivo:ConferencePaper": 128,
        "ucdrp:person": 14,
        "vivo:FacultyMember": 13,
        "bibo:Chapter": 8,
        "bibo:Book": 4,
        "vivo:NonAcademic": 2
      }
    },
    "ranges": {}
  }
}
```

**Comment by qjhart** [comment]
@jtyzzer can you verify these are all the citation types?

**Comment by jtyzzer** [comment]
@qhart: Looks like a blend of people and pubs, with the two kinds adding up to 771. The 757 pubs are broken down to academic articles, conference proceedings, chapters, and books. The people don't seem to add up quite right (15 vs. 14).

In the data set I have (pulled Friday) I only see academic articles, chapters, and books. Bibo shows academic articles and conference papers being subtypes of articles, and DocumentPart is parent of BookSection is parent of Chapter. Here's what I've seen in earlier iterations of our data (covid-centric):

|Document type | Count
|---------------|------|
| http://purl.org/ontology/bibo/Article | 700 |
| http://purl.org/ontology/bibo/AcademicArticle | 578 |
| http://vivoweb.org/ontology/core#ConferencePaper | 122 |
| http://purl.org/ontology/bibo/BookSection | 8 |
| http://purl.org/ontology/bibo/Chapter | 8 |
| http://purl.org/ontology/bibo/DocumentPart | 8 |
| http://purl.org/ontology/bibo/Book | 4 |

For a more complete listing (and mapping) see [this](https://docs.google.com/spreadsheets/d/19YuEd3B3IAhS9pM3Mpp9abZZ_5eojc7Uc8AsIdHoNZU/edit#gid=0) doc.

**Comment by qjhart** [comment]
@jtyzzer , This seems correct for the requirements here, however your query above indicates a problemt with the material science vivo schema.  See [gitlab Issue #3](https://gitlab.dams.library.ucdavis.edu/experts/experts-data/issues/3)

**Comment by jtyzzer** [comment]
Closed per @qjhart.
