### ISSUE TITLE
Update Search Boosts

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-client#341]
When / During completion of: 
- [x] https://github.com/ucd-library/vessel/issues/65
- [x] https://github.com/ucd-library/vessel/issues/64
- [x] https://github.com/ucd-library/research-profiles/issues/114
- [x] https://github.com/ucd-library/vessel/issues/66

Make the following updates to the default searches:

``` text
doi.text^10
hasContactInfo.familyName.text^9
hasContactInfo.givenName^8
hasContactInfo.middleName^8

abstract^1

hasResearchArea.label.text^1
hasPublicationVenue.issn^1
hasPublicationVenue.label.text^1

assignedBy.label.text
sponsorAwardId.text^2
relates.hasContactInfo.familyName^10
relates.hasContactInfo.givenName^10
assignedBy.label^10

role.relatedBy.label.text^11
role.relatedBy.sponsorAwardId.text^5

```

Remove:

``` text
__.personLabel.text^6
_.workLabel.text^6
_.grantLabel.text^6_
```

# https://github.com/ucd-library/vessel/issues/66

On completion:

``` text
hasSubjectArea.label.text^3
```

# https://github.com/ucd-library/vessel/issues/65

On completion 
``` text
### Increase boost as shown
label.text^7

### Delete b/c redundant with label.text
prefLabel.text^5
```

# https://github.com/ucd-library/vessel/issues/64

On completion

``` text
  citation.label^10
  _.plusCitation.label^5
```

**Comment by Vensberg** [comment]
Keep abstract.

**Comment by UcDust** [comment]
@Vensberg @qjhart 
Should prefLabel also be removed (and the label.text weight changed) in _concepts_? Right now, that's set to:

```
label.text^10
prefLabel.text^10
```

**Comment by Vensberg** [comment]
Good catch. Yes, it should be removed, but leave the weight the same.

**Comment by UcDust** [comment]
Thanks! Will do
