### ISSUE TITLE
Changes to "Edit Publication" pop-up

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/rp-ucd-client#39]
User testing showed that the link to UC publication management needs to be more prominent. I propose we change from how it currently looks (issue #17) to the design below:

![Web 1920 – Profile –  Pub Edit – 2](https://user-images.githubusercontent.com/17831969/99004194-94617580-24f3-11eb-8789-2bea5d1afdb2.png)

I'm not sure what design ramifications this has for issue #16 yet. TBD.

**Comment by Vensberg** [comment]
Change link to pending publications: https://oapolicy.universityofcalifornia.edu/objects.html?as=3&am=false&cid=1&ipr=false&iqf=true
