### ISSUE TITLE
"My profile" link should appear under username

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/rp-ucd-client#41]
Users need a direct way to get to their own profiles without having to search for themselves. A direct link to "My profile" should appear as an option above the logout option when the username is clicked on. 

![Screen Shot 2020-11-12 at 3 34 06 PM](https://user-images.githubusercontent.com/17831969/99009681-40f42500-24fd-11eb-84b4-e961b883a0eb.png)

**Comment by sbagg** [comment]
Add flag if user does or doesn't have profile
