### ISSUE TITLE
Research Subject Browse UI

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/rp-ucd-client#49]
The Browse page for Research Subjects will look exactly like the other ones ([People](https://dev.experts.ucdavis.edu/people), [Works](https://dev.experts.ucdavis.edu/works)), but with the research subject icon in a rec-pool colored circle (see issue #46). The link text will just be the subject term.

![Screen Shot 2020-12-11 at 5 59 21 PM](https://user-images.githubusercontent.com/17831969/101969682-a14cb400-3bda-11eb-9e4c-6a82fbdc0fb7.png)

I don't actually have a full page mock-up for this right now, but I'm not sure you need one since it follows the same format as everything else?

**Comment by jrmerz** [comment]
We should be ok without mockup but will let you know if this is a false statement.
