### ISSUE TITLE
Make sure Proxima Nova is being shipped with app 

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/rp-ucd-client#50]
Make sure the Proxima Nova fonts are being shipped with the app. I see it listed in the font stack, but the app currently renders for me in Lucida Grande.

**Comment by wrenaria** [comment]
Still rendering as Lucida Grande for me.

**Comment by wrenaria** [comment]
Weirdly, site appears to render Proxima Nova on my phone, but Lucida Grande (rendered locally) on my desktop? This happens on all browsers for both my work laptop and my personal computer.

**Comment by jrmerz** [comment]
This is because I'm and idiot and loaded Roboto. :) Will fix.
