### ISSUE TITLE
Add snippet to search results list ui

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#62]
Search results for people or works should have a snippet about why they matched with matched word in bold. Requires #61.  Sub #47, #46

**Comment by jrmerz** [comment]
@wrenaria For publications the work `title` is often the matched result for the `snippet`.  So the `title` and `snippet` in the UI are the same text.  You ok with this or would you prefer this case handled differently?

**Comment by wrenaria** [comment]
@jrmerz Looks like the new issue #87 addresses your lingering question (that we also discussed today), so moving this to done.
