### ISSUE TITLE
Remove filters for 'All' view

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#66]
Sub #46

**Comment by wrenaria** [comment]
The "All" view should not have filters displayed. The other tabs are correct, the "All" view is an exception. 

Screenshot from sandbox (+ my annotation):

![Screen Shot 2021-01-26 at 2 26 20 PM](https://user-images.githubusercontent.com/17831969/105914227-e5f1aa80-5fe2-11eb-9379-6b3260b66b87.png)

It should be like this:

![Screen Shot 2021-01-26 at 2 32 49 PM](https://user-images.githubusercontent.com/17831969/105914581-61ebf280-5fe3-11eb-86bc-990aa8b59504.png)

**Comment by wrenaria** [comment]
The paddings/margins/whatever need fixed for this view now that the filters are gone. There is extra space to the left of the results that shouldn't be there. It should match what is happening on the right side.

**Comment by spelkey-ucd** [comment]
@sbagg fyi, you will also have to adjust the [setPeopleWidth function](https://github.com/ucd-library/rp-ucd-client/blob/sandbox/client/public/elements/utils/rp-utils-collection.js#L365) to account for the missing filters sidebar.
