### ISSUE TITLE
Clean up footer

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#7]
- Make sure all links point at something.
 - Remove Powered by VIVO.
 - Add terms of use.

This issue is only addressing initial public launch.  Not the final version of the footer.

**Comment by jrmerz** [comment]
@qjhart @Vensberg Currently covid experts has the following terms of use page: https://covid-research.experts.library.ucdavis.edu/vivo/termsOfUse.  Should this be added to and linked in the footer of aggie experts?

**Comment by Vensberg** [comment]
@jrmerz any idea where that language came from?

**Comment by jrmerz** [comment]
@Vensberg that is a great question.  @qjhart @jtyzzer @wrenaria anyone remember? ... I forget.

**Comment by jtyzzer** [comment]
@jrmerz: No idea -- I think the addition of the terms of use preceded my joining the project.

**Comment by wrenaria** [comment]
@jrmerz I've never looked at this page before this very moment... So no. Sorry!

**Comment by qjhart** [comment]
I do not have that language in my emails.  It seems like something Michael would have crafted, but I don't know either.

**Comment by Vensberg** [comment]
Let's keep it. We may want to modify it down the road to reflect the data governance and policy principles we proposed for the project.

**Comment by Vensberg** [comment]
Quinn also modified the Terms of Use to reflect the non-commercial clause of ODR.
