### ISSUE TITLE
MIV Export button UI

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#8]
Official design

**Comment by qjhart** [comment]
@wrenaria, @Vensberg  is looking for a location to put some FAQ information about importing into MIV.  We don't want this on the main FAQ, since we are not supposed to name MIV on the public site, so we are wondering if we could possibly add some information on the export on/near this export button, which only shows up for the user.

**Comment by wrenaria** [comment]
@qjhart As the export button is designed currently -- https://github.com/ucd-library/research-profiles/issues/65 -- no, it wouldn't make a lot of sense to put that info there. I will have to redesign it if that's what you want. 

All these different repositories get confusing. Is this where designs like what I linked above should be placed, or should I keep putting them in researcher-profiles as I have been doing?

**Comment by wrenaria** [comment]
After discussing options with Vessela and showing possibilities displaying MIV import information, she would prefer to move forward with the design as originally described in ucd-library/research-profiles#65. I have copied and pasted the designs from there into this comment.

---

Simple as possible seems like the best solution for this: expose all download options on click, then click on the option you want to initiate the download. 

## Publications Download Design
![Web 1920 – Profile – Logged In – Download Pub](https://user-images.githubusercontent.com/17831969/93398911-4a308080-f831-11ea-8e47-32b176da28a9.png)

| mobile default | mobile clicked
| --- | ---
| <img src="https://user-images.githubusercontent.com/17831969/93398878-35ec8380-f831-11ea-8e88-15d38b92053e.png" width="250" > | <img src="https://user-images.githubusercontent.com/17831969/93398883-3a18a100-f831-11ea-90ac-3fc9f2825d28.png" width="250" >

## Button States

![Web 1920 – Profile – Logged In – Download Pub Specs](https://user-images.githubusercontent.com/17831969/93398868-3127cf80-f831-11ea-90b1-fb06eeea2ee8.png)
