### ISSUE TITLE
Add Research Subjects to Homepage

### ISSUE THREAD

**Issue by spelkey-ucd** [ucd-library/rp-ucd-client#82]

**Comment by wrenaria** [comment]
Hullo, your resident picky designer is here. The research subjects buttons on the home page aren't rounded enough. They have rectangley qualities, which is not quite right. Rectangling may be inevitable on multi-line subjects, but is undesirable on single line items. 

From current sandbox homepage:
![Screen Shot 2021-01-26 at 3 04 02 PM](https://user-images.githubusercontent.com/17831969/105917788-bbeeb700-5fe7-11eb-8b18-6ae5c2d45b85.png)

They look better/more correct on [profiles](https://sandbox.experts.ucdavis.edu/individual/ytakamur):

![Screen Shot 2021-01-26 at 3 04 50 PM](https://user-images.githubusercontent.com/17831969/105917880-dfb1fd00-5fe7-11eb-8dc2-42d21cc77708.png)

Though I do prefer the height of the homepage ones as they are a slightly more mobile-click-friendly scale. (That said, if the way it is currently on the profile is the best way to get perfect rounds, I can live with that.) Both these locations should have these subject buttons sized the same.
