### ISSUE TITLE
Add query for publications of a research subject.

### ISSUE THREAD

**Issue by spelkey-ucd** [ucd-library/rp-ucd-client#84]
re #48 

Need to display 5 most recent publications of each pub type on research subject landing page.

**Comment by wrenaria** [comment]
@spelkey-ucd Are subject page changes actually pushed to sandbox? Every subject I've clicked on thus far has the same lorem ipsum overview and related subjects lists, and empty researchers and publications list blocks.

**Comment by spelkey-ucd** [comment]
@wrenaria this card is just for the backend query, not the ui.

I believe Sabrina just finished the research subject landing page ui, which should include publications. Doesn't look like she has made a pull request into sandbox yet.

**Comment by wrenaria** [comment]
@spelkey-ucd Ahhh okay, got it. Thanks.
