### ISSUE TITLE
Allow admins to impersonate user

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#88]
This is only to see what the user sees, does not provide write access.  Simply a tool for QA.

**Comment by jrmerz** [comment]
@wrenaria and FYI for everyone. 

If a user is an admin, all profile pages (/individual/*) now show a 'Impersonate' button just under the research areas (hard to miss).  Click the button and the page should reload with you impersonated as the user.  To stop impersonating, click the username dropdown menu in the top right, there should be a button to 'Stop Impersonating'.

**Comment by wrenaria** [comment]
@jrmerz "Stop impersonation" is not always working. On desktop sometimes it won't let me at all, on mobile it gives me either a never ending "loading..." or this error: `Cannot GET / undefined`

**Comment by wrenaria** [comment]
@jrmerz When I impersonate a user and then click "my profile" from the user's options, it just hangs on "loading" and never loads anything. Not sure if this is a "my profile" link bug or an impersonation bug.

![Screen Shot 2021-02-09 at 2 41 09 PM](https://user-images.githubusercontent.com/17831969/107438490-6507d800-6ae5-11eb-9713-e617633c72c1.png)

**Comment by jrmerz** [comment]
I broke the "my profile" button .... But at least "impersonate" is giving you the full experience .......
