### ISSUE TITLE
Pagination showing '...' when not required

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#89]
Example search: http://localhost:8080/search?s=mechanical
There are 4 pages.  When on page one, the following is shown:

![Screen Shot 2021-01-26 at 3 17 06 PM](https://user-images.githubusercontent.com/1852393/105918893-9367bc80-5fe9-11eb-9b7a-513e5637d0b9.png)

**Comment by spelkey-ucd** [comment]
@sbagg I can take this one.

**Comment by wrenaria** [comment]
The "..." is only hiding one number which is completely unnecessary. We should only show ellipses if 2+ numbers are in that spot.

![Screen Shot 2021-01-28 at 4 18 43 PM](https://user-images.githubusercontent.com/17831969/106214894-9f3bb600-6184-11eb-8919-f2a3ffa8ddf9.png)

**Comment by spelkey-ucd** [comment]
@wrenaria ellipses should only appear for 2+ numbers
