### ISSUE TITLE
Publications edit button showing for all users

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#91]
The publications edit button (pencil icon) is showing for all users if they are logged in and have a profile.  It should only show if
 - The user is logged in
 - The user has a profile
 - The current page is the users profile page

**Comment by wrenaria** [comment]
The download publications list button should have the same rules as the edit button. T

**Comment by wrenaria** [comment]
I am still seeing the Download Publications button on all profiles. We only want people to be able to download their own publications. 

![Screen Shot 2021-02-01 at 4 31 45 PM](https://user-images.githubusercontent.com/17831969/106535571-5e58df80-64ab-11eb-9de8-dc92b50656b1.png)
