### ISSUE TITLE
Hide QR/permalink buttons on profiles

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/rp-ucd-client#97]
The QR and permalink buttons in the top right of profile pages are carry-overs from the original vivo layout, but they aren't currently functioning. If we aren't intending to wire them up to anything, they should go away/be hidden. (I'm not sure they are very useful, I am fine with removing them completely unless they are a feature @Vensberg wants to keep).

![Screen Shot 2021-01-28 at 4 40 27 PM](https://user-images.githubusercontent.com/17831969/106216277-9c8e9000-6187-11eb-9442-cd8647c5df92.png)
[profile example](https://sandbox.experts.ucdavis.edu/individual/benthem)

**Comment by Vensberg** [comment]
That's funny. I was clicking on them earlier today trying to figure out what they do. They can go.

**Comment by wrenaria** [comment]
@sbagg Did this for sure get pushed to sandbox? I'm still seeing these buttons on [peoples' profiles](https://sandbox.experts.ucdavis.edu/individual/rhcastro).
